### PR TITLE
Added retries as a parameter

### PR DESCRIPTION
**Pull request by pmav**
I have added n_retries as a optional parameter. I'm using this lib to monitor performance of DreamHost Objects and sometimes I get the "ran out of retries" message. Most of the times 2 or 3 retries are enough.

### CODE REVIEW

**Comment by lericson** [comment]
Then I recommend that you set the attributes on the instance explicitly, there is no need for yet another keyword argument to this very huge constructor already. This is how you do it:

``` python
b = S3Bucket(…)
b.n_retries = 10
```

**Comment by lericson** [comment]
I would be happy to accept the James the documents this better. What do you think?

**Comment by lericson** [comment]
by "the James" I mean "a change"

**Comment by pmav** [comment]
Sounds, good, what you have in mind?

**Comment by lericson** [comment]
Is there no docs directory or something like that? :)
- Ludvig (phone)

**Pull request closed without merging**
